### ISSUE TITLE
Instructions unclear on IR LED wiring in readme

### ISSUE THREAD

**Issue by AlexBezuska** [MKme/Roomba#2]
Hi there! Awesome project, I was excited to build one with a spare Arduino I had lying around so I ordered the LEDs and resistors you linked to on amazon, today they came but I ran into a snag when assembling.

**There might be a mix up in the readme.**
The Readme says  "IR LED with it's positive leg connected via a current-limiting resistor(220 Ohm or similar) to the +5v, and it's negative leg to Pin3 (hardcoded via library)"

But the table says the resistor goes on the negative leg/ D3 pin, also the photo shows the resistor on the negative leg/ D3 pin

 I have an Arduino board similar to the Sparkfun pro micro, it's one from ebay that has the same pins which I have used on other projects. I have tried both ways from the readme and cannot see the LED lit in a phone camera. I also tried the LED on 5v (VCC in my case) and ground and it lights up just fine in a phone camera

The pin I am using is 9 because the IRremote library readme says the "send pins" for my Sparkfun Pro Micro are 9, 5,5 (https://github.com/z3t0/Arduino-IRremote#hardware-specifications)

Any help you can provide is greatly appreciated, and thanks again for sharing your code and video!

**Comment by MKme** [comment]
It doesnt matter where you put a current limiting resistor- its a series circuit. It will limit the current
