### ISSUE TITLE
I found an error

### ISSUE THREAD

**Issue by ianyoon** [MKme/Roomba#3]
Arduino: 1.8.12 (Windows 10), Board: "Arduino Nano, ATmega328P"

RoombaArduinoVirtualWallEASY:16:10: fatal error: IRremote.h: No such file or directory

compilation terminated.

exit status 1
IRremote.h: No such file or directory

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by MKme** [comment]
This is an error telling you that you did not install the library. This is not something I can help you with.
